#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("bleissem.babyphone.Droid.Resource", IsApplication=true)]

namespace bleissem.babyphone.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::bleissem.babyphone.Droid.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::bleissem.babyphone.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::bleissem.babyphone.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::bleissem.babyphone.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int AmpTextView = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int ChooseContactButton = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int CloseButton = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int ContactTextView = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int ContactsDetailTextView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ContactsList = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int NoiseLevelButton = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int NoiseLevelTextView = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int PhoneNumberDetailTextView = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int PhoneNumberList = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int ServiceButton = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactsDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContactsMaster = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PhoneNumberDetail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PhoneNumberMaster = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ChooseContact = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int ChooseLabel = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int ChooseNoiseLevel = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int Close = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int Dialing = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int FeatureAvaiableSoon = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int StartService = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int StopService = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
