#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("bleissem.babyphone.Droid.Resource", IsApplication=true)]

namespace bleissem.babyphone.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::bleissem.babyphone.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::bleissem.babyphone.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int my_button = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int AmpTextView = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int CheckBoxEnableSkypeVideo = 2131099671;
			
			// aapt resource value: 0x7f060007
			public const int ChooseContactButton = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int ChoosePhoneButton = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ChoosePhoneLabelTextView = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int ChooseSkypeButton = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ChooseSkypeLabelTextView = 2131099650;
			
			// aapt resource value: 0x7f060015
			public const int ChooseSkypeOutButton = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int ChooseSkypeUserButton = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int ChooseSkypeUserOKButton = 2131099672;
			
			// aapt resource value: 0x7f060012
			public const int ChooseSkypeUserOrPhoneLabel1 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int ChooseSkypeUserOrPhoneLabel2 = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int ChooseSkypeUserText = 2131099670;
			
			// aapt resource value: 0x7f060008
			public const int ContactTextView = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int ContactsDetailTextView = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ContactsList = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int NoiseLevelButton = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int NoiseLevelTextView = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int PhoneNumberDetailTextView = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int PhoneNumberList = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int ServiceButton = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int StatusTextView = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int YouAreUsingLabeltextView = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int YouAreUsingTextView = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int textView2 = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChooseSkypeOrTelephone = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContactsDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContactsMaster = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PhoneNumberDetail = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PhoneNumberMaster = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SkypeChooseUserOrSkypePhone = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SkypeUser = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ChooseContact = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int ChooseLabel = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int ChooseNoiseLevel = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int ChoosePhoneLabel = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int ChooseSkypeLabel = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int ChooseSkypeOutButton = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int ChooseSkypeUserButton = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int ChooseSkypeUserOKButton = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int ChooseSkypeUserOrPhoneLabel1 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int ChooseSkypeUserOrPhoneLabel2 = 2130968590;
			
			// aapt resource value: 0x7f040012
			public const int ChooseSkypeVideo = 2130968594;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int Phone = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int Skype = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int SkypeOut = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int StartService = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int StatusTextNothing = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int StatusTextSleeping = 2130968596;
			
			// aapt resource value: 0x7f040007
			public const int StopService = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int YouAreUsingLabel = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int my_scrollview = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int my_text_black = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int my_text_white = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
