#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("babyphone.Resource", IsApplication=true)]

namespace babyphone
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int fab_margin = 2130837504;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int my_button = 2130903041;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int AmpTextView = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int CheckBoxEnableSkypeVideo = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ChooseContactButton = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ChoosePhoneButton = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ChoosePhoneLabelTextView = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int ChooseSkypeButton = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ChooseSkypeLabelTextView = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int ChooseSkypeOutButton = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int ChooseSkypeUserButton = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int ChooseSkypeUserOKButton = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ChooseSkypeUserOrPhoneLabel1 = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int ChooseSkypeUserOrPhoneLabel2 = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ChooseSkypeUserText = 2130968588;
			
			// aapt resource value: 0x7F04000E
			public const int ContactsDetailTextView = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int ContactsList = 2130968591;
			
			// aapt resource value: 0x7F04000D
			public const int ContactTextView = 2130968589;
			
			// aapt resource value: 0x7F04001B
			public const int fab = 2130968603;
			
			// aapt resource value: 0x7F040010
			public const int MainView = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int NoiseLevelButton = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int NoiseLevelTextView = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int PhoneAdditionalSettingsSpeakerCheckBox = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int PhoneAdditionalSettingsSpeakerOKButton = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int PhoneNumberDetailTextView = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int PhoneNumberList = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int ServiceButton = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int StatusTextView = 2130968600;
			
			// aapt resource value: 0x7F04001C
			public const int textView2 = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int toolbar = 2130968605;
			
			// aapt resource value: 0x7F040019
			public const int YouAreUsingLabeltextView = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int YouAreUsingTextView = 2130968602;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050009
			public const int activity_main = 2131034121;
			
			// aapt resource value: 0x7F050000
			public const int ChooseSkypeOrTelephone = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ContactsDetail = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ContactsMaster = 2131034114;
			
			// aapt resource value: 0x7F05000A
			public const int content_main = 2131034122;
			
			// aapt resource value: 0x7F050003
			public const int Main = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int PhoneNumberAdditionalSettings = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int PhoneNumberDetail = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int PhoneNumberMaster = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int SkypeChooseUserOrSkypePhone = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int SkypeUser = 2131034120;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int ic_launcher = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ic_launcher_foreground = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ic_launcher_round = 2131099650;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int BackLabel = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ChooseContact = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int ChooseLabel = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int ChooseNoiseLevel = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int ChoosePhoneLabel = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int ChooseSkypeLabel = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int ChooseSkypeOutButton = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int ChooseSkypeUserButton = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int ChooseSkypeUserOKButton = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int ChooseSkypeUserOrPhoneLabel1 = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int ChooseSkypeUserOrPhoneLabel2 = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int ChooseSkypeVideo = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int OKLabel = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int Phone = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int PhoneAdditionalSettingsSpeakerLabel = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int Skype = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int SkypeIsNotInstalledOK = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int SkypeIsNotInstalledText = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int SkypeIsNotInstalledTitle = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int SkypeOut = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int StartService = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int StatusTextNothing = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int StatusTextSleeping = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int StopService = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int YouAreUsingLabel = 2131165209;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppTheme = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int AppTheme_AppBarOverlay = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int AppTheme_NoActionBar = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int AppTheme_PopupOverlay = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int my_scrollview = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int my_text_black = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int my_text_white = 2131230726;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
